apiVersion: v1
kind: Service
metadata:
  name: cartcache
  namespace: dev-sandbox
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: coolstore-cartcache
  type: ClusterIP
