apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev-sandbox
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: coolstore-kafka
  type: ClusterIP
