apiVersion: v1
kind: Service
metadata:
  name: coolstoredb
  namespace: dev-sandbox
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: coolstore-coolstoredb
  type: ClusterIP
